version: '3.8'
services:
  nginx:
    container_name: "nginx_seons_crm"
    image: 'nginx:alpine3.18'
    restart: always
    ports:
      - 8080:80
    depends_on:
      - phpfpm
    environment:
      TZ: 'Asia/Novosibirsk'
    working_dir: /var/www
    volumes_from:
      - phpfpm
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      app_net:
        ipv4_address: 192.130.10.10
  phpfpm:
    container_name: "php_seons_crm"
    image: php_crm 
    build: 
      context: ./php
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    environment:
      TZ: 'Asia/Novosibirsk'
    restart: always
    working_dir: /var/www
    volumes:
     - ../seons-crm:/var/www
    networks:
      app_net:
        ipv4_address: 192.130.10.20
  mysql:
    container_name: 'mysql_seons_crm'
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      TZ: 'Asiz/Novosibirsk'
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_USER: 'seons'
      MYSQL_PASS: '123456'
      MYSQL_DATABASE: 'seons_crm'
    working_dir: /var/www
    command: 
       --character-set-server=utf8mb4
       --collation-server=utf8mb4_general_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/lib/logs
    networks:
      app_net:
        ipv4_address: 192.130.10.30
networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.130.0.0/16
          gateway: 192.130.10.100


